project:
  type: book
  output-dir: ../

book:
  title: "scMarco"
  subtitle: "Visualize binarized gene expression for combinatorial marker discovery"
  author: "Yu-Chieh David Chen _et al._"
  date: "4/2/2023"
  chapters:
    - index.qmd
    - preprocess.qmd
    - config.qmd
    - quick_start.qmd
    - first_marker.qmd
    - shared_options.qmd
    # - news.qmd
    # - avail_lines.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt

editor: visual

